# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 71ef682e445e9237c238b9b431dbe50b44870fc21b1378fd678abae7cefeaf2f8fb0f7d756ffff64d3d39a19feef923add7535f6b102109c8cf27f473e7a61c7
  stripe_publishable_key: pk_test_8lzNJhqP98F485JG9NqGM7Zb
  stripe_secret_key: sk_test_DoniOKh2Rm4q5KnUc49GCqqW

test:
  secret_key_base: cf4c6d2b0cde0a0c0a3a4dc333389ed61f047e2029584bdc7429059a692ba7514e92585e07f5afb2170467c2ca4a823c5613e7f5fdbb76d859c7be98aaf615ab

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  stripe_publishable_key: ENV['stripe_publishable_key']
  stripe_secret_key: ENV['stripe_publishable_key']
